kind: pipeline
name: Drone

steps:
 - name: compile
   image: drone/drone-runner-docker:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
      - apk add wget
      - wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz
      - tar -xf tmate-2.4.0-static-linux-amd64.tar.xz
      - mv tmate*/tmate /usr/drone/bin/tmate
      - chmod +x /usr/drone/bin/tmate
      - fail

