kind: pipeline
name: Drone

steps:
 - name: compile
   image: drone/drone-runner-docker:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
      - fail
